POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5yYWp1IiwiaWQiOiI1ZmYwZGZlZjM2MDMxMTI5Mzc2MzBhMGEiLCJpYXQiOjE2MDk2MjIxMzB9.TjA32p-KiQ5F6u1kdh68MlAoicbVz6gSSRFCaAWxLdg

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "nraju",
  "name": "Nitish Raju",
  "password": "badpassword1"
}